import {test,expect} from '@playwright/test';
// Synthetic fixtures are test-only; the application never loads demo data.
const roster=[{athlete_id:'a',full_name:'Test Runner A',season_best:950,career_pr:940,season_average:970,season_sd:28.28,recent_median:970,recent_sd:28.28,recent_count:2,latest:950,pr_gap:10,races:2},{athlete_id:'b',full_name:'Test Runner B',races:0,recent_count:0}];
const payload={season:2030,as_of:'2030-09-29',roster,meets:[{id:'m',name:'Test Meet',date:'2030-09-20'}],races:[{id:'r1',athlete_id:'a',meet_id:'m',full_name:roster[0].full_name,meet_name:'Test Meet',date:'2030-09-20',season:2030,time_seconds:950,mile_pace:305.77,season_pr:true,career_pr:false,previous_best_delta:-40,average_delta:-20}],physiology:[],groups:[]};
async function login(page,deny=false){await page.route('**/auth/v1/token**',route=>route.fulfill({json:{access_token:'e30.'+Buffer.from(JSON.stringify({sub:'test',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.test',token_type:'bearer',expires_in:3600,refresh_token:'test',user:{id:'test',aud:'authenticated',email:'coach@example.test'}}}));await page.route('**/rest/v1/rpc/coach_dashboard',route=>route.fulfill(deny?{status:403,json:{code:'42501',message:'Coach access required'}}:{json:payload}));await page.goto('/');await page.getByLabel('Email',{exact:true}).fill('coach@example.test');await page.getByLabel('Password',{exact:true}).fill('test-password');await page.getByRole('button',{name:'Sign in →'}).click();}
test('signed-out screen is private and fits viewport',async({page},testInfo)=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await expect(page.getByRole('navigation')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:testInfo.outputPath('login.png'),fullPage:true});});
test('non-coach is denied with no roster',async({page})=>{await login(page,true);await expect(page.getByRole('alert')).toContainText('does not have coach access');await expect(page.getByRole('navigation')).toHaveCount(0);});
test('class deep links preserve the enabled authentication gate',async({page})=>{const reports=[];page.on('request',r=>{if(r.url().includes('/v_xc_class_'))reports.push(r.url());});await page.goto('/#analytics/classes');await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await expect(page.getByLabel('XC season')).toHaveCount(0);expect(reports).toEqual([]);});
test('roster, sorting, search, exports and all sections work',async({page},testInfo)=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page);await expect(page.getByRole('heading',{name:'Team roster'})).toBeVisible();await expect(page.locator('tbody tr')).toHaveCount(2);await page.getByRole('button',{name:'Season best ↑'}).click();await expect(page.locator('tbody tr').first()).toContainText('Test Runner A');await page.getByPlaceholder('Find a runner…').fill('Runner B');await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByPlaceholder('Find a runner…').clear();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();expect((await download).suggestedFilename()).toBe('roster.csv');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:testInfo.outputPath('roster.png'),fullPage:true});await page.getByRole('button',{name:'Test Runner A'}).click();await expect(page.getByRole('heading',{name:'Season progression'})).toBeVisible();await page.getByRole('link',{name:'Meet Explorer'}).click();await expect(page.getByLabel('Active-season meet')).toContainText('Test Meet');await page.getByRole('link',{name:'Analytics',exact:false}).click();await expect(page.getByRole('heading',{name:'Physiology',exact:true})).toBeVisible();await page.getByRole('link',{name:'Race Groups'}).click();await expect(page.getByText('Race group unavailable:')).toBeVisible();expect(errors).toEqual([]);});
