import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {client, requireCoachAuth} from './client';
import {time, number, delta, sortRows, delimited, unavailable} from './format';
import './style.css';

const col = (key, label, format = time) => ({key,label,format});
const rosterCols = [col('full_name','Athlete',String),col('season_best','Season best'),col('career_pr','All-time PR'),col('season_average','Season average'),col('season_sd','Season SD'),col('recent_median','Recent 3 median'),col('recent_sd','Recent 3 SD'),col('recent_count','Recent n',number),col('latest','Latest result'),col('pr_gap','PR gap',delta),col('races','Races',number)];
const pr = v => v == null ? unavailable : v ? 'PR' : '—';
const raceCols = [col('date','Date',String),col('meet_name','Meet',String),col('time_seconds','Time'),col('mile_pace','Mile pace'),col('mile_1','1-mile split'),col('mile_2','2-mile split'),col('overall_position','Overall position',number),col('team_position','Team position',number),col('season_pr','Season PR',pr),col('career_pr','All-time PR',pr),col('previous_best_delta','Δ previous best',delta),col('average_delta','Δ season average',delta)];
const improvementCols = [rosterCols[0],col('season_best','Season best'),col('improvement','Season improvement',delta),col('improvement_pct','Improvement %',number),col('previous_season_best','Previous season best'),col('year_improvement','Year improvement',delta)];
const tabs = ['Roster','Athlete Performance','Meet Explorer','Analytics','Race Groups'];
const slugs = ['roster','athlete','meets','analytics','groups'];
function Table({rows,columns,initialSort,filename,onAthlete}) {
  const [sort,setSort] = useState({key:initialSort || columns[0].key,direction:1});
  const [notice,setNotice] = useState('');
  const sorted = sortRows(rows,sort.key,sort.direction);
  function download() { const url=URL.createObjectURL(new Blob(['\uFEFF'+delimited(columns,sorted)],{type:'text/csv;charset=utf-8'})); const a=document.createElement('a'); a.href=url; a.download=filename+'.csv'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
  async function copy() { try {await navigator.clipboard.writeText(delimited(columns,sorted,'\t'));setNotice('Table copied.');} catch {setNotice('Clipboard unavailable. Use CSV export.');} }
  return <section className="table-panel"><div className="table-tools"><span>{rows.length} {rows.length===1?'row':'rows'}</span><div><button onClick={copy}>Copy table</button><button onClick={download}>↓ Export CSV</button></div><span role="status">{notice}</span></div><div className="table-scroll" tabIndex="0" aria-label="Scrollable results table"><table><thead><tr>{columns.map(c=><th key={c.key} aria-sort={sort.key===c.key?(sort.direction===1?'ascending':'descending'):'none'}><button onClick={()=>setSort({key:c.key,direction:sort.key===c.key?-sort.direction:1})}>{c.label} <span>{sort.key===c.key?(sort.direction===1?'↑':'↓'):'↕'}</span></button></th>)}</tr></thead><tbody>{sorted.map((r,i)=><tr key={r.id||r.athlete_id||i}>{columns.map(c=><td key={c.key}>{c.key==='full_name'&&onAthlete?<button className="athlete-link" onClick={()=>onAthlete(r.athlete_id)}>{r.full_name}<span>↗</span></button>:<span className={r[c.key]==null?'muted':c.key.endsWith('_pr')&&r[c.key]===true?'badge':''}>{r[c.key]==null?unavailable:c.format(r[c.key])}</span>}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No qualifying results available.</div>}</div></section>;
}
function Cards({items}) {return <div className="cards">{items.map(([label,value])=><div className="card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>;}
function Chart({races,athlete}) {
  const [avg,setAvg]=useState(true),[best,setBest]=useState(true);
  if (!races.length) return <div className="panel empty">No current-season races to chart.</div>;
  const vals=races.map(r=>r.time_seconds), min=Math.min(...vals)-10,max=Math.max(...vals)+10;
  const dates=races.map(r=>Date.parse(r.date)), start=Math.min(...dates),end=Math.max(...dates);
  const x=d=>70+(end===start?0.5:(d-start)/(end-start))*810,y=v=>35+(v-min)/(max-min)*185;
  return <section className="panel"><div className="section-head"><h2>Season progression</h2><div><label><input type="checkbox" checked={avg} onChange={e=>setAvg(e.target.checked)}/> Average</label> <label><input type="checkbox" checked={best} onChange={e=>setBest(e.target.checked)}/> Best</label></div></div><svg className="chart" viewBox="0 0 950 275" role="img" aria-label="Chronological race times; faster times appear higher. Exact values are in the race history table.">{[min,(min+max)/2,max].map(v=><g key={v}><line x1="70" x2="900" y1={y(v)} y2={y(v)} stroke="#303830"/><text x="0" y={y(v)+5}>{time(v)}</text></g>)}{avg&&<line x1="70" x2="900" y1={y(athlete.season_average)} y2={y(athlete.season_average)} stroke="#b2c7d9" strokeDasharray="8 6"/>}{best&&<line x1="70" x2="900" y1={y(athlete.season_best)} y2={y(athlete.season_best)} stroke="#d4af37" strokeDasharray="3 5"/>}<polyline points={races.map(r=>`${x(Date.parse(r.date))},${y(r.time_seconds)}`).join(' ')} fill="none" stroke="#d4af37" strokeWidth="3"/>{races.map(r=><circle key={r.id} cx={x(Date.parse(r.date))} cy={y(r.time_seconds)} r="5" fill="#d4af37"><title>{r.date} · {r.meet_name} · {time(r.time_seconds)}</title></circle>)}<text x="70" y="260">{races[0].date}</text><text x="900" y="260" textAnchor="end">{races.at(-1).date}</text></svg><p className="muted">Gold dotted: season best · Blue dashed: season average · Faster times appear higher.</p></section>;
}
function Login({session,error,busy,onLogin,onLogout,onRetry}) {
  const [email,setEmail]=useState(''),[password,setPassword]=useState('');
  return <div className="login-wrap"><div className="login-intro"><div className="eyebrow">NOBLESVILLE BOYS CROSS COUNTRY</div><h1>Know the numbers.<br/><em>Coach the runner.</em></h1><p>Your team’s season, performance, and race plans in one place.</p><div className="track-art" aria-hidden="true"><i/><i/><i/></div></div><section className="login-panel"><span className="eyebrow">COACH PORTAL</span><h2>{session?'Coach access':'Welcome back'}</h2><p className="muted">Sign in with your authorized coaching account.</p>{!client?<p role="alert">Supabase configuration is missing or invalid. Set the public environment values described in the README and rebuild.</p>:session?<><p role="alert">{error||'Checking coach access…'}</p><button disabled={busy} onClick={onRetry}>Retry access</button><button onClick={onLogout}>Sign out</button></>:<form onSubmit={e=>{e.preventDefault();onLogin(email,password);}}><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in →'}</button></form>}<p className="fine">Access is assigned by your team administrator. Contact them for account or password assistance.</p></section></div>;
}
function App() {
  const [session,setSession]=useState(null),[dashboard,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [tab,setTab]=useState(slugs.includes(location.hash.slice(1))?location.hash.slice(1):'roster');
  const [athleteId,setAthleteId]=useState(''),[meetId,setMeetId]=useState(''),[search,setSearch]=useState('');
  const request=useRef(0);
  const data=dashboard || (!requireCoachAuth ? {season:'',as_of:'Unavailable',roster:[],races:[],meets:[],physiology:[],groups:[]} : null);
  useEffect(()=>{if(!client||!requireCoachAuth)return;const {data:{subscription}}=client.auth.onAuthStateChange((_event,s)=>{request.current++;setSession(s);setData(null);setError('');});return()=>subscription.unsubscribe();},[]);
  async function load(){const token=++request.current;setBusy(true);setError('');try{if(!client)throw Error('Supabase configuration is missing or invalid.');const {data:d,error:e}=await client.rpc(requireCoachAuth?'coach_dashboard':'coach_public_dashboard');if(token!==request.current)return;if(e)throw e;if(!d||!Array.isArray(d.roster))throw Error('Unexpected server response.');setData(d);setAthleteId(id=>d.roster.some(a=>a.athlete_id===id)?id:d.roster[0]?.athlete_id||'');setMeetId(id=>d.meets.some(m=>m.id===id)?id:d.meets.find(m=>m.date<=d.as_of)?.id||d.meets[0]?.id||'');}catch(e){if(token===request.current){setData(null);setError(!requireCoachAuth ? 'Public dashboard data is unavailable. Existing database permissions may restrict a required dataset. '+e.message : e.code==='42501'?'This account does not have coach access. Ask your administrator to add it to the coach allowlist.':'Unable to load coach data. '+e.message);}}finally{if(token===request.current)setBusy(false);}}
  useEffect(()=>{if(!requireCoachAuth||session)load();else setBusy(false);},[session]);
  useEffect(()=>{const change=()=>setTab(slugs.includes(location.hash.slice(1))?location.hash.slice(1):'roster');window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
  async function login(email,password){setBusy(true);setError('');try{const {error:e}=await client.auth.signInWithPassword({email,password});if(e)throw e;}catch(e){setError(e.message);setBusy(false);}}
  async function logout(){request.current++;setData(null);setSession(null);setBusy(false);const {error:e}=await client.auth.signOut({scope:'local'});if(e)setError('Sign-out request failed; local dashboard has been cleared.');}
  function openAthlete(id){setAthleteId(id);location.hash='athlete';}
  const athlete=data?.roster.find(a=>a.athlete_id===athleteId), races=data?.races.filter(r=>r.season===data.season)||[], history=races.filter(r=>r.athlete_id===athleteId), meetRows=races.filter(r=>r.meet_id===meetId);
  const group=data?.groups.find(g=>g.athlete_id===athleteId),phys=data?.physiology.find(p=>p.athlete_id===athleteId);
  const switcher=<label className="switcher">Athlete<select value={athleteId} onChange={e=>setAthleteId(e.target.value)}>{data?.roster.map(a=><option key={a.athlete_id} value={a.athlete_id}>{a.full_name}</option>)}</select></label>;
  return <><header className="topbar"><a className="brand" href="#roster">PACE<span>RIGHT</span><small>COACH</small></a><span className="team">Noblesville High School <span> / </span> Boys XC</span>{requireCoachAuth&&session&&<button onClick={logout}>Sign out</button>}</header>{!data?<Login {...{session,error,busy}} onLogin={login} onLogout={logout} onRetry={load}/>:<div className="app-shell"><aside><div className="eyebrow">TEAM WORKSPACE</div><nav aria-label="Main navigation">{tabs.map((t,i)=><a key={t} href={'#'+slugs[i]} aria-current={tab===slugs[i]?'page':undefined}><span className="nav-index">0{i+1}</span>{t}</a>)}</nav><div className="season-chip"><span className="live-dot"/> {data.season} season<small>Active roster · Read only</small></div></aside><main><div className="page-head"><div><div className="eyebrow">{data.season} CROSS COUNTRY</div><h1>{tabs[slugs.indexOf(tab)]}</h1><p className="muted">{tab==='roster'?'Every runner. A clearer view of the season.':'Noblesville boys · Current active roster'}</p></div><button disabled={busy} onClick={load}>{busy?'Refreshing…':'↻ Refresh'}</button></div>
  {!requireCoachAuth&&!dashboard&&<section className="panel" role={error?'alert':'status'}>{error || 'Loading public dashboard...'}</section>}
  {dashboard&&tab==='roster'&&<><Cards items={[["Active athletes",data.roster.length],["Athletes with results",data.roster.filter(a=>a.races>0).length],["Season meets",data.meets.length],["Data as of",data.as_of]]}/><div className="section-head"><h2>Team roster</h2><label className="search">Search athletes<input type="search" placeholder="Find a runner…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><Table rows={data.roster.filter(a=>a.full_name.toLowerCase().includes(search.toLowerCase()))} columns={rosterCols} initialSort="season_best" filename="roster" onAthlete={openAthlete}/><p className="fine">XC 5K results only. Recent statistics use up to three active-season races. SD is sample standard deviation (n − 1); unavailable for fewer than two races.</p></>}
  {dashboard&&tab==='athlete'&&<>{switcher}{athlete?<><h2 className="athlete-title">{athlete.full_name}</h2><Cards items={rosterCols.filter(c=>!['full_name','latest'].includes(c.key)).map(c=>[c.label,c.format(athlete[c.key])])}/><Chart races={history} athlete={athlete}/><h2>Current-season race history</h2><Table rows={history} columns={raceCols} filename="athlete-history" initialSort="date"/><p className="fine">First recorded results establish a PR baseline; ties are not new PRs. Previous best uses strictly earlier dates. Splits and positions are not recorded in the current schema.</p><h2>Career progression</h2><Table rows={data.races.filter(r=>r.athlete_id===athleteId)} columns={[...raceCols.slice(0,4),col('best_to_date','Season best to date')]} filename="career-progression" initialSort="date"/></>:<div className="empty">No active athletes available.</div>}</>}
  {dashboard&&tab==='meets'&&<><label className="switcher">Active-season meet<select value={meetId} onChange={e=>setMeetId(e.target.value)}>{data.meets.map(m=><option key={m.id} value={m.id}>{m.date} · {m.name}</option>)}</select></label><Cards items={(()=>{const n=new Set(meetRows.map(r=>r.athlete_id)).size;const s=new Set(meetRows.filter(r=>r.season_pr).map(r=>r.athlete_id)).size,c=new Set(meetRows.filter(r=>r.career_pr).map(r=>r.athlete_id)).size;const deltas=meetRows.filter(r=>r.previous_best_delta!=null);return [['Active athletes racing',n],['Season PRs',`${s} / ${n?number(s/n*100)+'%':'Unavailable'}`],['All-time PRs',`${c} / ${n?number(c/n*100)+'%':'Unavailable'}`],['Mean Δ previous best',delta(deltas.length?deltas.reduce((s,r)=>s+r.previous_best_delta,0)/deltas.length:null)]];})()}/><Table rows={meetRows} columns={[rosterCols[0],...raceCols.slice(2)]} initialSort="time_seconds" filename="meet-results" onAthlete={openAthlete}/><p className="fine">Only active-athlete qualifying XC 5K results are shown. PR comparisons exclude later and same-day races. Percentages count distinct athletes, including first-result baselines. Δ season average uses the full season to date.</p></>}
  {dashboard&&tab==='analytics'&&<><h2>Season improvement</h2><p className="muted">First result minus season best. Positive improvement means faster; year comparison uses the previous calendar season.</p><Table rows={data.roster} columns={improvementCols} filename="season-improvement" onAthlete={openAthlete}/><h2>Consistency</h2><Table rows={data.roster} columns={[rosterCols[0],...rosterCols.slice(3,8),rosterCols[10]]} filename="consistency" onAthlete={openAthlete}/><p className="fine">Sample SD = √(Σ(time − mean)² / (n − 1)). Recent n reports the available sample, up to three results.</p><h2>Physiology</h2><Table rows={data.roster.map(a=>({...a,...data.physiology.find(p=>p.athlete_id===a.athlete_id)}))} columns={[rosterCols[0],col('vdot_current','Current VDOT',number),col('vdot_xc_pr','Weighted PR VDOT',number),col('ser_value','SER',number),col('ser_primary_source','SER source',String),col('ser_confidence','SER confidence',number),col('sir_seconds','SIR',delta)]} filename="physiology" onAthlete={openAthlete}/><div className="panel"><h3>Reading the metrics</h3><p>VDOT is the existing race-performance estimate, combining track and 5K PRs with current-season results. SER is the existing weighted log time/distance exponent; a source of “vdot_fallback” is an estimate. SIR is 1600m PR minus twice the 800m PR, in seconds.</p><h3>Race execution & weather adjustment</h3><p className="muted">Unavailable. The current results schema has no mile or halfway splits. The existing weather-adjusted views are fixed to 2025, so they cannot supply reliable current-season adjustments.</p></div></>}
  {dashboard&&tab==='groups'&&<>{switcher}<h2 className="athlete-title">{athlete?.full_name||'No active athlete'}</h2><Cards items={[["Current VDOT",number(phys?.vdot_current)],["Weighted PR VDOT",number(phys?.vdot_xc_pr)],["Season average",time(athlete?.season_average)],["Career XC 5K PR",time(athlete?.career_pr)]]}/>{!group?<div className="panel empty">Race group unavailable: insufficient authoritative VDOT data.</div>:<><div className="panel"><span className="eyebrow">EXISTING PACERIGHT RACE PLAN</span><h2>{group.talk_to_blake?'Talk to Blake':'Packmates & stretch anchors'}</h2><p>{group.anchor_reason}</p><p className="muted">{group.talk_to_blake?'The existing varsity override applies. The comparison athletes below are informational.':'Packmates are the existing three faster and two similar/slower comparisons, where available.'}</p></div><Table rows={['faster_1','faster_2','faster_3','peer_1','peer_2','anchor_1','anchor_2'].map((k,i)=>({id:k,role:i<3?'Faster '+(i+1):i<5?'Similar/slower '+(i-2):'Stretch anchor '+(i-4),full_name:group[k],vdot:group[k+'_vdot'],career_pr:data.roster.find(a=>a.athlete_id===group[k+'_id'])?.career_pr}))} columns={[col('role','Comparison',String),rosterCols[0],col('vdot','VDOT',number),col('career_pr','Career XC 5K PR')]} filename="race-groups"/><p className="fine">Read directly from v_athlete_xc_race_neighborhood. Existing VDOT weighting, ±1.25 comparison band, anchor targeting and varsity overrides are preserved.</p></>}</>}
  <footer>PACE<span>RIGHT</span> <span> / </span> Coach with context.</footer></main></div>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
